#!/bin/bash

if [[ "$1" == "-q" ]] || [[ "$1" == "-Q" ]]; then
	QUICK="$1"
	MESSAGE=""
else
	MESSAGE="$1"
	QUICK="$2"
fi

if [[ -z "$MESSAGE" ]]; then
	MESSAGE="deployed on `date`"
fi


mkdir -p deploy

cd deploy

# Testa se já tem o diretorio do projeto, se não faz o clone
if [ ! -d fislgames ]; then
  echo "[info] clonando o repositorio na openshift"
  git clone ssh://51c452225973cad476000015@fislgames-exmo.rhcloud.com/~/git/fislgames.git/
fi

# Entra no diretorio do projeto
cd fislgames

echo "[info] sincronizando com o repositorio"
git pull

# Adiciona o projeto do Github
git remote add github -m master git@github.com:exmo/fislGamesSerpro.git
echo "[info] sincronizando com o github"
git pull -s recursive -X theirs github master



if [[ "$QUICK" == "-q" ]] || [[ "$QUICK" == "-Q" ]]; then
	echo "[info] running: play stage"
	play stage
else
	echo "[info] running: play clean compile stage"
	play clean compile stage
fi

echo "[info] running: git add . -A"
git add . -A

echo "[info] running: git commit -m \"$MESSAGE\""
git commit -m "$MESSAGE"

echo "[info] running: git push origin"
git push origin


